apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: my-service
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: "http"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "80"
  spec:
    ports:
      - name: app
        port: 80
        targetPort: 80
    selector:
      app: my-service

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-service
  spec:
    selector:
      matchLabels:
        app: my-service
    template:
      metadata:
        labels:
          app: my-service
      spec:
        containers:
          - name: nginx
            image: "nginx:alpine"
            ports:
              - containerPort: 80
                protocol: TCP
            volumeMounts:
              - mountPath: /usr/share/nginx/html
                name: www-volume
        volumes:
          - name: www-volume
            configMap:
              name: www
    replicas: 1

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: www
  data:
    index.html: |
      Hello World
    metrics: |
      my_metric 1
    alerts: |
      groups:
      - name: test.rules
        rules:
        - alert: JustTest
          expr: up{job="kubernetes-nodes"} == 0
          for: 5s
          annotations:
            summary: "Node is down"
